### ISSUE TITLE
zabbix 3.0 4.0 Installation errors!

### ISSUE THREAD

**Issue by zengxc-1996** [Websoft9Archive/ansible-zabbix#16]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [x] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [x] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [x] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

# bug error
After experiment,The Zabbix-SnmpTraps do not start properly.
There is a problem with the image, 3.0 and 4.0 Damage of the mirror

![image](https://user-images.githubusercontent.com/63622990/117937803-f4b56080-b338-11eb-8bf5-76207fdd6705.png)

![image](https://user-images.githubusercontent.com/63622990/117937971-1f071e00-b339-11eb-91be-f22cb27d4382.png)

# service status 
![image](https://user-images.githubusercontent.com/63622990/117936977-106c3700-b338-11eb-9522-6203067fece5.png)

# error logs
![image](https://user-images.githubusercontent.com/63622990/117936989-1530eb00-b338-11eb-9b83-003e2f2cc63b.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by chendelin1982** [comment]
use docker image
